defmodule Stytch.AuthenticationFactor do
  @moduledoc """
  Provides struct and type for a AuthenticationFactor
  """
  use Stytch.Schema

  @type t :: %__MODULE__{
          amazon_oauth_factor: Stytch.AuthenticationFactor.AmazonOAuth.t() | nil,
          apple_oauth_factor: Stytch.AuthenticationFactor.AppleOAuth.t() | nil,
          authenticator_app_factor: Stytch.AuthenticationFactor.AuthenticatorApp.t() | nil,
          biometric_factor: Stytch.AuthenticationFactor.Biometric.t() | nil,
          bitbucket_oauth_factor: Stytch.AuthenticationFactor.BitbucketOAuth.t() | nil,
          coinbase_oauth_factor: Stytch.AuthenticationFactor.CoinbaseOAuth.t() | nil,
          created_at: DateTime.t() | nil,
          crypto_wallet_factor: Stytch.AuthenticationFactor.CryptoWallet.t() | nil,
          delivery_method: String.t(),
          discord_oauth_factor: Stytch.AuthenticationFactor.DiscordOAuth.t() | nil,
          email_factor: Stytch.AuthenticationFactor.Email.t() | nil,
          embeddable_magic_link_factor: Stytch.AuthenticationFactor.EmbeddableMagicLink.t() | nil,
          facebook_oauth_factor: Stytch.AuthenticationFactor.FacebookOAuth.t() | nil,
          figma_oauth_factor: Stytch.AuthenticationFactor.FigmaOAuth.t() | nil,
          git_lab_oauth_factor: Stytch.AuthenticationFactor.GitLabOAuth.t() | nil,
          github_oauth_exchange_factor: Stytch.AuthenticationFactor.GithubOAuthExchange.t() | nil,
          github_oauth_factor: Stytch.AuthenticationFactor.GithubOAuth.t() | nil,
          google_oauth_exchange_factor: Stytch.AuthenticationFactor.GoogleOAuthExchange.t() | nil,
          google_oauth_factor: Stytch.AuthenticationFactor.GoogleOAuth.t() | nil,
          hubspot_oauth_exchange_factor:
            Stytch.AuthenticationFactor.HubspotOAuthExchange.t() | nil,
          hubspot_oauth_factor: Stytch.AuthenticationFactor.HubspotOAuth.t() | nil,
          impersonated_factor: Stytch.AuthenticationFactor.Impersonated.t() | nil,
          instagram_oauth_factor: Stytch.AuthenticationFactor.InstagramOAuth.t() | nil,
          last_authenticated_at: DateTime.t() | nil,
          linked_in_oauth_factor: Stytch.AuthenticationFactor.LinkedInOAuth.t() | nil,
          microsoft_oauth_factor: Stytch.AuthenticationFactor.MicrosoftOAuth.t() | nil,
          oauth_access_token_exchange_factor:
            Stytch.AuthenticationFactor.OAuthAccessTokenExchange.t() | nil,
          oidc_sso_factor: Stytch.AuthenticationFactor.OIDCSSO.t() | nil,
          phone_number_factor: Stytch.AuthenticationFactor.PhoneNumber.t() | nil,
          recovery_code_factor: Stytch.AuthenticationFactor.RecoveryCode.t() | nil,
          salesforce_oauth_factor: Stytch.AuthenticationFactor.SalesforceOAuth.t() | nil,
          saml_sso_factor: Stytch.AuthenticationFactor.SAMLSSO.t() | nil,
          shopify_oauth_factor: Stytch.AuthenticationFactor.ShopifyOAuth.t() | nil,
          slack_oauth_exchange_factor: Stytch.AuthenticationFactor.SlackOAuthExchange.t() | nil,
          slack_oauth_factor: Stytch.AuthenticationFactor.SlackOAuth.t() | nil,
          snapchat_oauth_factor: Stytch.AuthenticationFactor.SnapchatOAuth.t() | nil,
          spotify_oauth_factor: Stytch.AuthenticationFactor.SpotifyOAuth.t() | nil,
          steam_oauth_factor: Stytch.AuthenticationFactor.SteamOAuth.t() | nil,
          tik_tok_oauth_factor: Stytch.AuthenticationFactor.TikTokOAuth.t() | nil,
          twitch_oauth_factor: Stytch.AuthenticationFactor.TwitchOAuth.t() | nil,
          twitter_oauth_factor: Stytch.AuthenticationFactor.TwitterOAuth.t() | nil,
          type: String.t(),
          updated_at: DateTime.t() | nil,
          webauthn_factor: Stytch.AuthenticationFactor.WebAuthn.t() | nil,
          yahoo_oauth_factor: Stytch.AuthenticationFactor.YahooOAuth.t() | nil
        }

  defstruct [
    :amazon_oauth_factor,
    :apple_oauth_factor,
    :authenticator_app_factor,
    :biometric_factor,
    :bitbucket_oauth_factor,
    :coinbase_oauth_factor,
    :created_at,
    :crypto_wallet_factor,
    :delivery_method,
    :discord_oauth_factor,
    :email_factor,
    :embeddable_magic_link_factor,
    :facebook_oauth_factor,
    :figma_oauth_factor,
    :git_lab_oauth_factor,
    :github_oauth_exchange_factor,
    :github_oauth_factor,
    :google_oauth_exchange_factor,
    :google_oauth_factor,
    :hubspot_oauth_exchange_factor,
    :hubspot_oauth_factor,
    :impersonated_factor,
    :instagram_oauth_factor,
    :last_authenticated_at,
    :linked_in_oauth_factor,
    :microsoft_oauth_factor,
    :oauth_access_token_exchange_factor,
    :oidc_sso_factor,
    :phone_number_factor,
    :recovery_code_factor,
    :salesforce_oauth_factor,
    :saml_sso_factor,
    :shopify_oauth_factor,
    :slack_oauth_exchange_factor,
    :slack_oauth_factor,
    :snapchat_oauth_factor,
    :spotify_oauth_factor,
    :steam_oauth_factor,
    :tik_tok_oauth_factor,
    :twitch_oauth_factor,
    :twitter_oauth_factor,
    :type,
    :updated_at,
    :webauthn_factor,
    :yahoo_oauth_factor
  ]

  @doc false
  @spec __fields__(atom) :: keyword
  def __fields__(type \\ :t)

  def __fields__(:t) do
    [
      amazon_oauth_factor: {Stytch.AuthenticationFactor.AmazonOAuth, :t},
      apple_oauth_factor: {Stytch.AuthenticationFactor.AppleOAuth, :t},
      authenticator_app_factor: {Stytch.AuthenticationFactor.AuthenticatorApp, :t},
      biometric_factor: {Stytch.AuthenticationFactor.Biometric, :t},
      bitbucket_oauth_factor: {Stytch.AuthenticationFactor.BitbucketOAuth, :t},
      coinbase_oauth_factor: {Stytch.AuthenticationFactor.CoinbaseOAuth, :t},
      created_at: {:string, :date_time},
      crypto_wallet_factor: {Stytch.AuthenticationFactor.CryptoWallet, :t},
      delivery_method: {:string, :generic},
      discord_oauth_factor: {Stytch.AuthenticationFactor.DiscordOAuth, :t},
      email_factor: {Stytch.AuthenticationFactor.Email, :t},
      embeddable_magic_link_factor: {Stytch.AuthenticationFactor.EmbeddableMagicLink, :t},
      facebook_oauth_factor: {Stytch.AuthenticationFactor.FacebookOAuth, :t},
      figma_oauth_factor: {Stytch.AuthenticationFactor.FigmaOAuth, :t},
      git_lab_oauth_factor: {Stytch.AuthenticationFactor.GitLabOAuth, :t},
      github_oauth_exchange_factor: {Stytch.AuthenticationFactor.GithubOAuthExchange, :t},
      github_oauth_factor: {Stytch.AuthenticationFactor.GithubOAuth, :t},
      google_oauth_exchange_factor: {Stytch.AuthenticationFactor.GoogleOAuthExchange, :t},
      google_oauth_factor: {Stytch.AuthenticationFactor.GoogleOAuth, :t},
      hubspot_oauth_exchange_factor: {Stytch.AuthenticationFactor.HubspotOAuthExchange, :t},
      hubspot_oauth_factor: {Stytch.AuthenticationFactor.HubspotOAuth, :t},
      impersonated_factor: {Stytch.AuthenticationFactor.Impersonated, :t},
      instagram_oauth_factor: {Stytch.AuthenticationFactor.InstagramOAuth, :t},
      last_authenticated_at: {:string, :date_time},
      linked_in_oauth_factor: {Stytch.AuthenticationFactor.LinkedInOAuth, :t},
      microsoft_oauth_factor: {Stytch.AuthenticationFactor.MicrosoftOAuth, :t},
      oauth_access_token_exchange_factor:
        {Stytch.AuthenticationFactor.OAuthAccessTokenExchange, :t},
      oidc_sso_factor: {Stytch.AuthenticationFactor.OIDCSSO, :t},
      phone_number_factor: {Stytch.AuthenticationFactor.PhoneNumber, :t},
      recovery_code_factor: {Stytch.AuthenticationFactor.RecoveryCode, :t},
      salesforce_oauth_factor: {Stytch.AuthenticationFactor.SalesforceOAuth, :t},
      saml_sso_factor: {Stytch.AuthenticationFactor.SAMLSSO, :t},
      shopify_oauth_factor: {Stytch.AuthenticationFactor.ShopifyOAuth, :t},
      slack_oauth_exchange_factor: {Stytch.AuthenticationFactor.SlackOAuthExchange, :t},
      slack_oauth_factor: {Stytch.AuthenticationFactor.SlackOAuth, :t},
      snapchat_oauth_factor: {Stytch.AuthenticationFactor.SnapchatOAuth, :t},
      spotify_oauth_factor: {Stytch.AuthenticationFactor.SpotifyOAuth, :t},
      steam_oauth_factor: {Stytch.AuthenticationFactor.SteamOAuth, :t},
      tik_tok_oauth_factor: {Stytch.AuthenticationFactor.TikTokOAuth, :t},
      twitch_oauth_factor: {Stytch.AuthenticationFactor.TwitchOAuth, :t},
      twitter_oauth_factor: {Stytch.AuthenticationFactor.TwitterOAuth, :t},
      type: {:string, :generic},
      updated_at: {:string, :date_time},
      webauthn_factor: {Stytch.AuthenticationFactor.WebAuthn, :t},
      yahoo_oauth_factor: {Stytch.AuthenticationFactor.YahooOAuth, :t}
    ]
  end
end
